var found = true;
var grade = 88.6;
var firstName = "Anu";
var lastName = 'Kumar';
// found = 0;
// grade = "A";
// firstName = false;
console.log(found);
console.log("The grade is " + grade);
console.log("Hi " + firstName + " " + lastName);
console.log("Hi ".concat(firstName, " ").concat(lastName));
